version: "3"

services:
  phoenix:
    build:
      context: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - .:/app:rw
    depends_on:
      cassandra:
        condition: service_healthy
      redis:
        condition: service_healthy

  cassandra:
    image: cassandra
    ports:
      - 9042:9042
      - 7199:7199
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces",
        ]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./schema.cql:/schema.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"

  redis:
    image: redis:6.2.6-alpine
    command: redis-server --requirepass redis_password
    volumes:
      - redis-data:/data:rw
    ports:
      - 6379/tcp
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 2s
      timeout: 5s

volumes:
  cassandra-data: {}
  redis-data: {}
